# Generated by Django 5.0.2 on 2024-03-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_student_affiliation_student_user_profile'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(max_length=255, verbose_name='소속'),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
    ]
