# Generated by Django 5.0.2 on 2024-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_license_userprofile_total_report_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='license',
            field=models.IntegerField(default=5, verbose_name='사용권(남은 횟수)'),
        ),
    ]
