# Generated by Django 5.0.2 on 2024-05-31 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_telephone_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="핸드폰 번호는 다음의 형식이어야 합니다 : '000-0000-0000'.", regex='^\\d{3}-\\d{4}-\\d{4}$')], verbose_name='핸드폰 번호'),
        ),
    ]
