# Generated by Django 5.0.2 on 2024-03-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearSemester', models.PositiveIntegerField(default=20231, verbose_name='YEAR_AND_SEMESTER')),
                ('TestGrade', models.PositiveSmallIntegerField(default=1, verbose_name='TEST_GRADE')),
                ('AnswerList', models.JSONField(default=list, verbose_name='ANSWER_LIST')),
                ('StrongPoint', models.JSONField(default=list, verbose_name='STRONG_POINT')),
                ('WeakPoint', models.JSONField(default=list, verbose_name='WEAK_POINT')),
                ('AccumulatedNumber', models.JSONField(default=list, verbose_name='ACCUMULATED_NUMBER')),
                ('AccumulatedRatio', models.JSONField(default=list, verbose_name='ACCUMULATED_RATIO')),
                ('NationalAverage', models.FloatField(default=0.0, verbose_name='NATIONAL_AVERAGE')),
                ('SeoulAverage', models.FloatField(default=0.0, verbose_name='SEOUL_AVERAGE')),
                ('SeoulRegionAverage', models.JSONField(default=list, verbose_name='SEOULRegion_AVERAGE')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamYearSemester', models.PositiveIntegerField(verbose_name='EXAM_YEAR_AND_SEMESTER')),
                ('ExamGrade', models.PositiveSmallIntegerField(verbose_name='EXAM_GRADE')),
                ('ExamArea', models.TextField(max_length=50, verbose_name='EXAM_AREA')),
                ('ExamResults', models.JSONField(default=list, verbose_name='EXAM_RESULTS')),
            ],
        ),
    ]
