# Generated by Django 5.0.2 on 2024-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_YearSemester', models.PositiveIntegerField(default=20231, verbose_name='YEAR_AND_SEMESTER')),
                ('Student_TestGrade', models.PositiveSmallIntegerField(default=1, verbose_name='TEST_GRADE')),
                ('Student_AnswerList', models.JSONField(default=list, verbose_name='ANSWER_LIST')),
                ('Student_StrongPoint', models.JSONField(default=list, verbose_name='STRONG_POINT')),
                ('Student_WeakPoint', models.JSONField(default=list, verbose_name='WEAK_POINT')),
                ('Student_AccumulatedNumber', models.JSONField(default=list, verbose_name='ACCUMULATED_NUMBER')),
                ('Student_AccumulatedRatio', models.JSONField(default=list, verbose_name='ACCUMULATED_RATIO')),
                ('Student_NationalAverage', models.FloatField(default=0.0, verbose_name='NATIONAL_AVERAGE')),
                ('Student_SeoulAverage', models.FloatField(default=0.0, verbose_name='SEOUL_AVERAGE')),
                ('Student_SeoulRegionAverage', models.JSONField(default=list, verbose_name='SEOULRegion_AVERAGE')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.PositiveIntegerField(verbose_name='STUDENTID')),
                ('ExamYearSemester', models.PositiveIntegerField(verbose_name='EXAM_YEAR_AND_SEMESTER')),
                ('ExamGrade', models.PositiveSmallIntegerField(verbose_name='EXAM_GRADE')),
                ('ExamArea', models.TextField(max_length=50, verbose_name='EXAM_AREA')),
                ('ExamResults', models.JSONField(default=list, verbose_name='EXAM_RESULTS')),
            ],
        ),
        migrations.CreateModel(
            name='TestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statistics_YearSemester', models.PositiveIntegerField(default=20231, verbose_name='YEAR_AND_SEMESTER')),
                ('Statistics_TestGrade', models.PositiveSmallIntegerField(default=1, verbose_name='TEST_GRADE')),
                ('Statistics_AnswerList', models.JSONField(default=list, verbose_name='ANSWER_LIST')),
                ('Statistics_StrongPoint', models.JSONField(default=list, verbose_name='STRONG_POINT')),
                ('Statistics_WeakPoint', models.JSONField(default=list, verbose_name='WEAK_POINT')),
                ('Statistics_AccumulatedNumber', models.JSONField(default=list, verbose_name='ACCUMULATED_NUMBER')),
                ('Statistics_AccumulatedRatio', models.JSONField(default=list, verbose_name='ACCUMULATED_RATIO')),
                ('Statistics_NationalAverage', models.FloatField(default=0.0, verbose_name='NATIONAL_AVERAGE')),
                ('Statistics_SeoulAverage', models.FloatField(default=0.0, verbose_name='SEOUL_AVERAGE')),
                ('Statistics_SeoulRegionAverage', models.JSONField(default=list, verbose_name='SEOULRegion_AVERAGE')),
            ],
        ),
    ]
