# Generated by Django 5.0.2 on 2024-03-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='TotalAverage',
            field=models.JSONField(default=list, verbose_name='TOTAL_AVERAGE'),
        ),
    ]
