# Generated by Django 5.0.2 on 2024-03-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='StudentId',
            field=models.PositiveIntegerField(default=0, verbose_name='STUDENTID'),
        ),
    ]
