# Generated by Django 5.0.2 on 2024-03-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_testresult_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatistics',
            name='Statistics_ProblemType',
            field=models.JSONField(default=list, verbose_name='PROBLEM_TYPE'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='StudentId',
            field=models.PositiveIntegerField(default=5, verbose_name='STUDENTID'),
        ),
    ]
