# Generated by Django 5.0.2 on 2024-03-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_testreport_totalaverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='TotalAverage',
        ),
    ]
