# Generated by Django 5.0.2 on 2024-03-26 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_teststatistics_statistics_problemtype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestReport',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(9999, 1, 1), verbose_name='Test_date'),
            preserve_default=False,
        ),
    ]
