# Generated by Django 5.0.2 on 2024-03-12 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_testreport_totalaverage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestReport',
            new_name='TestStatistics',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='AccumulatedNumber',
            new_name='Statistics_AccumulatedNumber',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='AccumulatedRatio',
            new_name='Statistics_AccumulatedRatio',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='AnswerList',
            new_name='Statistics_AnswerList',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='NationalAverage',
            new_name='Statistics_NationalAverage',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='SeoulAverage',
            new_name='Statistics_SeoulAverage',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='SeoulRegionAverage',
            new_name='Statistics_SeoulRegionAverage',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='StrongPoint',
            new_name='Statistics_StrongPoint',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='TestGrade',
            new_name='Statistics_TestGrade',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='WeakPoint',
            new_name='Statistics_WeakPoint',
        ),
        migrations.RenameField(
            model_name='teststatistics',
            old_name='YearSemester',
            new_name='Statistics_YearSemester',
        ),
    ]
