# Generated by Django 5.0.2 on 2024-03-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_rename_testreport_teststatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_YearSemester', models.PositiveIntegerField(default=20231, verbose_name='YEAR_AND_SEMESTER')),
                ('Student_TestGrade', models.PositiveSmallIntegerField(default=1, verbose_name='TEST_GRADE')),
                ('Student_AnswerList', models.JSONField(default=list, verbose_name='ANSWER_LIST')),
                ('Student_StrongPoint', models.JSONField(default=list, verbose_name='STRONG_POINT')),
                ('Student_WeakPoint', models.JSONField(default=list, verbose_name='WEAK_POINT')),
                ('Student_AccumulatedNumber', models.JSONField(default=list, verbose_name='ACCUMULATED_NUMBER')),
                ('Student_AccumulatedRatio', models.JSONField(default=list, verbose_name='ACCUMULATED_RATIO')),
                ('Student_NationalAverage', models.FloatField(default=0.0, verbose_name='NATIONAL_AVERAGE')),
                ('Student_SeoulAverage', models.FloatField(default=0.0, verbose_name='SEOUL_AVERAGE')),
                ('Student_SeoulRegionAverage', models.JSONField(default=list, verbose_name='SEOULRegion_AVERAGE')),
            ],
        ),
    ]
