# Generated by Django 5.0.2 on 2024-03-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_test_report_student_delete_test_and_more'),
        ('report', '0004_delete_testreport_testresult_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student'),
        ),
    ]
