# Generated by Django 5.0.2 on 2024-03-27 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_test_report_student_delete_test_and_more'),
        ('report', '0005_testresult_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='dashboard.student'),
        ),
    ]
