# Generated by Django 5.0.2 on 2024-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_testresult_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatistics',
            name='Statistics_ScoreList',
            field=models.JSONField(default=list, verbose_name='SCORE_LIST'),
        ),
        migrations.AlterField(
            model_name='teststatistics',
            name='Statistics_AccumulatedNumber',
            field=models.JSONField(default=list, null=True, verbose_name='ACCUMULATED_NUMBER'),
        ),
        migrations.AlterField(
            model_name='teststatistics',
            name='Statistics_AccumulatedRatio',
            field=models.JSONField(default=list, null=True, verbose_name='ACCUMULATED_RATIO'),
        ),
    ]
