# Generated by Django 5.0.2 on 2024-02-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Test_list',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Consulting_content',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Consulting_schedule',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Consulting_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Test_date',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('test_date', models.DateField(auto_now_add=True, verbose_name='Test_date')),
                ('consulting_schedule', models.DateTimeField(blank=True, null=True, verbose_name='SCHEDULE')),
                ('consulting_content', models.TextField(blank=True, help_text='상담 내용을 적으세요.', max_length=200, verbose_name='CONTENT')),
                ('consulting_status', models.BooleanField(default=False, verbose_name='CONSULTING STATUS')),
                ('student', models.ManyToManyField(blank=True, to='dashboard.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Test_list',
        ),
    ]
