# Generated by Django 5.0.2 on 2024-03-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_student_test_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_report',
            name='student',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test_report',
        ),
    ]
