# Generated by Django 5.0.2 on 2024-03-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_student_affiliation_student_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_profile',
        ),
    ]
